# Generated by Django 5.0.4 on 2024-05-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Social",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site",
                    models.CharField(
                        choices=[
                            ("facebook", "\ue810"),
                            ("instagram", "\ue807"),
                            ("x", "\ue829"),
                            ("youtube", "\ue82e"),
                            ("linkedin", "\ue819"),
                        ],
                        default="facebook",
                        max_length=20,
                        verbose_name="Site",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, max_length=100, null=True, verbose_name="URL"
                    ),
                ),
                (
                    "added_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        null=True,
                        verbose_name="Creation date",
                    ),
                ),
                (
                    "last_modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated date",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Link",
                "verbose_name_plural": "Social Links",
                "ordering": ("-last_modified_date",),
            },
        ),
    ]
