# Generated by Django 5.0.4 on 2024-05-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0002_alter_social_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="social",
            name="site",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("x", "X"),
                    ("youtube", "YouTube"),
                    ("linkedin", "LinkedIn"),
                ],
                default="facebook",
                max_length=20,
                verbose_name="Site",
            ),
        ),
    ]
