# Generated by Django 5.0.4 on 2024-06-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0004_social_share_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="social",
            name="nickname",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nickname"
            ),
        ),
    ]
