# Generated by Django 5.0.4 on 2024-06-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AlterField(
            model_name="user",
            name="email_confirmed",
            field=models.BooleanField(default=False, verbose_name="Email confirmed"),
        ),
    ]
