# Generated by Django 5.0.4 on 2024-05-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_userprofile_id_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(upload_to="user_images/"),
        ),
    ]
