# Generated by Django 5.0.4 on 2024-05-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_userprofile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(blank=True, upload_to="user_images/"),
        ),
    ]
