# Generated by Django 5.0.4 on 2024-06-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_ai_bot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="ai_bot",
            field=models.BooleanField(default=False, verbose_name="AI Bot"),
        ),
    ]
