version: "3.3"
services:  
  redis:
    image: redis:latest
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
  
  flower:
    image: mher/flower
    environment:
    - CELERY_BROKER_URL=redis://redis:6379/0
    - FLOWER_PORT=5555
    expose:
      - 5555
    depends_on:
      redis:
        condition: service_healthy

  django:
    # build: ./blog
    image: wobidobi/prod:latest
    # restart: always
    volumes:
      - media_wobidobi:/var/www/media
      - static_wobidobi:/var/www/static
    env_file:
      - ./.env
    expose:
      - "8000"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - media_wobidobi:/var/www/media
      - static_wobidobi:/var/www/static
    depends_on:
      django:
        condition: service_healthy
    ports:
      - "80:80"

volumes:
  media_wobidobi:
  static_wobidobi: