version: "3.3"
services:
  db:
    image: postgres:16.0-alpine
    networks:
      - wobidobi-network
    volumes:
      - data_wobidobi:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 3s
      retries: 3
  
  redis:
    image: redis:latest
    networks:
      - wobidobi-network
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
  
  flower:
    image: mher/flower
    networks:
      - wobidobi-network
    environment:
    - CELERY_BROKER_URL=redis://redis:6379/0
    - FLOWER_PORT=5555
    expose:
      - 5555
    depends_on:
      redis:
        condition: service_healthy

  django:
    image: wobidobi/prod:latest
    restart: always
    networks:
      - wobidobi-network
    volumes:
      - media_wobidobi:/var/www/media
      - static_wobidobi:/var/www/static
    expose:
      - "8000"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:latest
    networks:
      - wobidobi-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - media_wobidobi:/var/www/media
      - static_wobidobi:/var/www/static
    depends_on:
      django:
        condition: service_healthy
    ports:
      - "80:80"

networks:
  wobidobi-network:

volumes:
  data_wobidobi:
  media_wobidobi:
  static_wobidobi: