version: "3.3"
services:
  db:
    image: postgres:16.0-alpine
    networks:
      - wobidobi-network
    volumes:
      - data_wobidobi:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 3s
      retries: 3
  
  redis:
    image: redis:latest
    networks:
      - wobidobi-network
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
  
  flower:
    image: mher/flower
    networks:
      - wobidobi-network
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      FLOWER_PORT: 5555
    expose:
      - 5555
    depends_on:
      redis:
        condition: service_healthy

  django:
    image: wobidobi/prod:latest
    restart: always
    networks:
      - wobidobi-network
    volumes:
      - media_wobidobi:/var/www/media
      - static_wobidobi:/var/www/static
    expose:
      - "8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      INTERNAL_IPS: ${INTERNAL_IPS}
      RECAPTCHA_PUBLIC_KEY: ${RECAPTCHA_PUBLIC_KEY}
      RECAPTCHA_PRIVATE_KEY: ${RECAPTCHA_PRIVATE_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DEBUG: ${DEBUG}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PORT: ${DB_PORT}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      CELERY_SINGLETON_BACKEND_URL: ${CELERY_SINGLETON_BACKEND_URL}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:latest
    networks:
      - wobidobi-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - media_wobidobi:/var/www/media
      - static_wobidobi:/var/www/static
    depends_on:
      django:
        condition: service_healthy
    ports:
      - "80:80"

networks:
  wobidobi-network:
    external: true

volumes:
  data_wobidobi:
  media_wobidobi:
  static_wobidobi: