services:  
  redis:
    image: redis:latest
    container_name: wd-redis
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
  
  flower:
    image: mher/flower
    container_name: wd-flower
    environment:
    - CELERY_BROKER_URL=redis://redis:6379/0
    - FLOWER_PORT=5555
    volumes:
      - flower_data:/data
    expose:
      - 5555
    depends_on:
      redis:
        condition: service_healthy

  django:
    image: wobidobi/prod:latest
    container_name: wd-django
    restart: always
    volumes:
      - media_wobidobi:/var/www/media
      - static_wobidobi:/var/www/static
    env_file:
      - ./.env
    expose:
      - "8000"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: wd-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./ads.txt:/opt/ads.txt:ro
      - ./robots.txt:/opt/robots.txt:ro
      - /etc/ssl/:/etc/ssl/
      - media_wobidobi:/var/www/media
      - static_wobidobi:/var/www/static
    ports:
      - "80:80"
      - "443:443"

volumes:
  media_wobidobi:
  static_wobidobi:
  redis_data:
  flower_data: