# Generated by Django 5.0.4 on 2024-05-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessedLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField(unique=True)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
