# Generated by Django 5.0.4 on 2024-05-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processedlink",
            name="link",
            field=models.URLField(db_index=True, unique=True),
        ),
    ]
