# Generated by Django 5.0.4 on 2024-06-06 14:26

import posts.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Comment")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created date"
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
            },
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Follow",
                "verbose_name_plural": "Follows",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Group name")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("description", models.TextField(verbose_name="Group description")),
            ],
            options={
                "verbose_name": "Group",
                "verbose_name_plural": "Groups",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        null=True,
                        validators=[posts.validators.validate_post_name],
                        verbose_name="Title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        null=True,
                        unique=True,
                        validators=[posts.validators.validate_slug],
                        verbose_name="Slug",
                    ),
                ),
                (
                    "short_text",
                    models.TextField(
                        blank=True,
                        db_index=True,
                        max_length=95,
                        verbose_name="Short text",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        validators=[posts.validators.validate_links_in_input],
                        verbose_name="Body",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="posts/",
                        validators=[
                            posts.validators.validate_image_size,
                            posts.validators.validate_file_extension,
                        ],
                        verbose_name="Image",
                    ),
                ),
                ("feature", models.BooleanField(default=False, verbose_name="Feature")),
                (
                    "pub_date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Publish date",
                    ),
                ),
                ("paid", models.BooleanField(default=False, verbose_name="Paid")),
                (
                    "published",
                    models.BooleanField(default=False, verbose_name="Published"),
                ),
                (
                    "added_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        null=True,
                        verbose_name="Creation date",
                    ),
                ),
                (
                    "last_modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Updated date",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ("-pub_date",),
            },
        ),
    ]
