# Generated by Django 5.0.4 on 2024-06-13 14:41

import core.utils
import posts.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="added_date",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                null=True,
                verbose_name="Creation date",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="last_modified_date",
            field=models.DateTimeField(
                auto_now=True, db_index=True, null=True, verbose_name="Updated date"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                upload_to=core.utils.RenameImgPathToSlug("posts/images"),
                validators=[
                    posts.validators.validate_image_size,
                    posts.validators.validate_file_extension,
                ],
                verbose_name="Image",
            ),
        ),
    ]
