# Generated by Django 2.2.9 on 2020-05-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200522_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.TextField(),
        ),
    ]
