# Generated by Django 2.2.6 on 2021-08-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20210822_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Укажите название группы латинскими буквами'),
        ),
    ]
