# Generated by Django 5.0.4 on 2024-05-03 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0014_auto_20210910_0504"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name": "Comment", "verbose_name_plural": "Comments"},
        ),
        migrations.AlterModelOptions(
            name="group",
            options={"verbose_name": "Group", "verbose_name_plural": "Groups"},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ("-pub_date",),
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
        ),
        migrations.AddField(
            model_name="post",
            name="added_date",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                null=True,
                verbose_name="Creation date",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="feature",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="last_modified_date",
            field=models.DateTimeField(
                auto_now=True, db_index=True, null=True, verbose_name="Updated date"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, null=True, verbose_name="Slug"),
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.TextField(
                blank=True, max_length=100, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created date"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="posts.post",
                verbose_name="Article",
            ),
        ),
        migrations.AlterField(
            model_name="follow",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="description",
            field=models.TextField(verbose_name="Group description"),
        ),
        migrations.AlterField(
            model_name="group",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="group",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Group name"),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="posts.group",
                verbose_name="Group",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="posts/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="pub_date",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Publish date"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(blank=True, verbose_name="Body"),
        ),
    ]
