# Generated by Django 5.0.4 on 2024-05-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0015_alter_comment_options_alter_group_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Title"
            ),
        ),
    ]
