# Generated by Django 5.0.4 on 2024-05-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0016_alter_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="short_text",
            field=models.TextField(blank=True, max_length=95, verbose_name="Body"),
        ),
    ]
