# Generated by Django 5.0.4 on 2024-05-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0017_post_short_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="paid",
            field=models.BooleanField(default=False, verbose_name="Paid"),
        ),
        migrations.AddField(
            model_name="post",
            name="published",
            field=models.BooleanField(default=False, verbose_name="Published"),
        ),
        migrations.AlterField(
            model_name="post",
            name="feature",
            field=models.BooleanField(default=False, verbose_name="Feature"),
        ),
    ]
