# Generated by Django 5.0.4 on 2024-05-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0018_post_paid_post_published_alter_post_feature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, null=True, verbose_name="Publish date"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="short_text",
            field=models.TextField(
                blank=True, db_index=True, max_length=95, verbose_name="Short text"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(blank=True, db_index=True, verbose_name="Body"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="Title",
            ),
        ),
    ]
