# Generated by Django 5.0.4 on 2024-05-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0019_alter_post_pub_date_alter_post_short_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="pub_date",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Publish date"
            ),
        ),
    ]
