# Generated by Django 5.0.4 on 2024-05-04 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0020_alter_post_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="posts.group",
                verbose_name="Group",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(upload_to="posts/", verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(null=True, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(db_index=True, verbose_name="Body"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                db_index=True, max_length=100, null=True, verbose_name="Title"
            ),
        ),
    ]
