# Generated by Django 5.0.4 on 2024-06-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0022_alter_post_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(verbose_name="Comment"),
        ),
    ]
