# Generated by Django 5.0.4 on 2024-05-29 21:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContactPage",
            new_name="Contact",
        ),
    ]
